AWSTemplateFormatVersion: 2010-09-09
Description: Create S3
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub test-bucket-${AWS::AccountId}-stacksets
